### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by CADuke** [james-atkinson/speedcomplainer#10]
# 

 Starting Speed Complainer!           
#  Lets get noisy!                      

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "speedcomplainer.py", line 99, in run
    speedTestResults = self.doSpeedTest()
  File "speedcomplainer.py", line 117, in doSpeedTest
    uploadResult = resultSet[2]
IndexError: list index out of range

Did I mess something up or missing something?

**Comment by manid** [comment]
Do you get this everytime? Looks like the speedtest has not been able to do both the uplaod/download tests.

**Comment by CADuke** [comment]
Yep every time. speedtest --simple runs on its own. Next step when I have time is to type all the code out. I don't know how many times I have had problems with copy/paste or downloading someone's code and something simple like a space be a space.

**Comment by manid** [comment]
@CADuke Check that the path to your speedtest-cli is correct in speedcomplainer.py
`result = os.popen("/usr/local/bin/speedtest-cli --simple").read()`

**Comment by CADuke** [comment]
@manid I tried changing locations of speedtest. I just tried a different python code and it came up with a bunch of errors, get an error for any code that uses installed packages.

**Comment by joetech** [comment]
Try to run just `speedtest` from the command line.  If it fails to get a server list, then follow the instructions listed in the first post here: https://forums.bunsenlabs.org/viewtopic.php?id=961
