### ISSUE TITLE
Error: Invalid control character - OSMC

### ISSUE THREAD

**Issue by laithalsunni** [james-atkinson/speedcomplainer#21]
Hi so I'm trying to git this working on OSMC. I have it running on raspian. how ever I'm getting this error when I run it on OSMC

```
osmc@osmc:~/speedcomplainer$ python speedcomplainer.py
======================================
 Starting Speed Complainer
 Lets get noisy
======================================
Error: Invalid control character at: line 12 column 81 (char 326)
```

any one know what I need to do?

**Comment by pilisera** [comment]
My guess would be that it's complaining about line 12 in the config. Did you make any changes to the config file? Can you try cutting out the "5" threshold and seeing if that changes the error? It could be a JSON parsing bug, since line 12 column 80 is a `{` character.
