### ISSUE TITLE
Need help with python datetime tweet

### ISSUE THREAD

**Issue by DarthKeizer** [james-atkinson/speedcomplainer#26]
Could anyone be kind enough to help me out? I wanted to post the datetime along with the rest of the tweet and I just could not get it to work. Can anyone help me out? It should be easy, but for the life of me I cant figure it out :(.

- I think in the JSON file you could make {date}
- In the python file at twitter message return {date.time} ?

**Comment by craigusus** [comment]
Hi @DarthKeizer,

I added
```
i = datetime.now()
```
On line 15 of speedcomplainer.py

Then edited (what is now) lines 144 - 146
```
if api:
tweet = message + i.strftime('%d/%m/%y @ %H:%M:%S')
status = api.PostUpdate(tweet)
```

Then added a single space at the end of each "tweetThresholds" in config.json to create a space between the end of the tweet and the timestamp.

![screen shot 2017-07-25 at 10 30 32](https://user-images.githubusercontent.com/6324863/28565503-5f7ee6b2-7124-11e7-83c7-8665497d7f53.png)

**Comment by craigusus** [comment]
No idea if it is 100% correct. But it works ! :wink:

**Comment by DarthKeizer** [comment]
Works, sorry for the super late reply haha!
