### ISSUE TITLE
Import daemon fails

### ISSUE THREAD

**Issue by bill7979** [james-atkinson/speedcomplainer#6]
I am new at this but really like the idea behind this so I am trying to get it up and running.  I am seeing a failure in Line 5 ImportError: No module named Daemon
Have I not installed a requirement for this to run?  Please let me know or if you have a step by step somewhere that would be great.  I am putting the steps together as I go and will be happy to share what I have once I get it working.

-Bill

**Comment by tannerhearne** [comment]
Hey @bill7979 - I forked this repo and added a few additions like a requirements.txt file to use with virtualenv and Twilio (SMS) support.  Checkout the requirements.txt file here: https://github.com/tannerhearne/speedcomplainer/blob/master/requirements.txt

**Comment by bill7979** [comment]
Thanks Tanner, issue is resolved.  One small suggestion is the Requirements.txt file be updated to include python-twitter as I just installed twitter and got an API Module issue.  Thanks again for your help.

**Comment by tannerhearne** [comment]
Ah!  I've been having the same issue @bill7979 - thanks for pointing that out!

**Comment by kevincannon** [comment]
Could I ask a really stupid question? I don't know python at all, but want to run the script.

I see from the requirements document, I need to install the daemon module - how do I actually do that?

Thanks

**Comment by joetech** [comment]
For those unaware of how to fix this:
1. Head to https://pypi.python.org/pypi/python-daemon/ in a browser and copy the link to the download for this module.  Then, on the pi, download it with `wget` followed by the link you copied.
2. Once downloaded, extract with `tar -zxvf` followed by the name of the downloaded file.
3. Now `cd` into the extracted module directory and run `python setup install`

Once installed, it should work, but you may have to install other modules (like twitter) in a similar fashion.
